import resource, {
  calculateFood,
  calculateWood,
  calculateBrick,
  calculateStone,
  calculateGold
} from './resource'

describe('Resource', () => {
  describe('Rolling dice', () => {
    describe('Food', () => {
      test('calculate the food received', () => {
        expect(calculateFood(1)).toBe(0)
        expect(calculateFood(2)).toBe(1)
        expect(calculateFood(3)).toBe(1)
        expect(calculateFood(4)).toBe(2)
      })
      test('calculate the received wood and check the resource total', () => {
        expect(calculateWood(1)).toBe(0)
        expect(resource.wood).toBe(30)
        expect(calculateWood(2)).toBe(0)
        expect(resource.wood).toBe(30)
        expect(calculateWood(3)).toBe(1)
        expect(resource.wood).toBe(29)
        expect(calculateWood(4)).toBe(1)
        expect(resource.wood).toBe(28)
        expect(calculateWood(5)).toBe(1)
        expect(resource.wood).toBe(27)
        expect(calculateWood(6)).toBe(2)
        expect(resource.wood).toBe(25)
      })
      test('calculate the received brick and check the resource total', () => {
        expect(calculateBrick(1)).toBe(0)
        expect(resource.brick).toBe(30)
        expect(calculateBrick(2)).toBe(0)
        expect(resource.brick).toBe(30)
        expect(calculateBrick(3)).toBe(0)
        expect(resource.brick).toBe(30)
        expect(calculateBrick(4)).toBe(1)
        expect(resource.brick).toBe(29)
        expect(calculateBrick(5)).toBe(1)
        expect(resource.brick).toBe(28)
        expect(calculateBrick(6)).toBe(1)
        expect(resource.brick).toBe(27)
        expect(calculateBrick(7)).toBe(1)
        expect(resource.brick).toBe(26)
        expect(calculateBrick(8)).toBe(2)
        expect(resource.brick).toBe(24)
      })
      test('calculate the received stone and check the resource total', () => {
        expect(calculateStone(1)).toBe(0)
        expect(resource.stone).toBe(30)
        expect(calculateStone(2)).toBe(0)
        expect(resource.stone).toBe(30)
        expect(calculateStone(3)).toBe(0)
        expect(resource.stone).toBe(30)
        expect(calculateStone(4)).toBe(0)
        expect(resource.stone).toBe(30)
        expect(calculateStone(5)).toBe(1)
        expect(resource.stone).toBe(29)
        expect(calculateStone(6)).toBe(1)
        expect(resource.stone).toBe(28)
        expect(calculateStone(7)).toBe(1)
        expect(resource.stone).toBe(27)
        expect(calculateStone(8)).toBe(1)
        expect(resource.stone).toBe(26)
        expect(calculateStone(9)).toBe(1)
        expect(resource.stone).toBe(25)
        expect(calculateStone(10)).toBe(2)
        expect(resource.stone).toBe(23)
      })
      test('calculate the received gold and check the resource total', () => {
        expect(calculateGold(1)).toBe(0)
        expect(resource.gold).toBe(30)
        expect(calculateGold(2)).toBe(0)
        expect(resource.gold).toBe(30)
        expect(calculateGold(3)).toBe(0)
        expect(resource.gold).toBe(30)
        expect(calculateGold(4)).toBe(0)
        expect(resource.gold).toBe(30)
        expect(calculateGold(5)).toBe(0)
        expect(resource.gold).toBe(30)
        expect(calculateGold(6)).toBe(1)
        expect(resource.gold).toBe(29)
        expect(calculateGold(7)).toBe(1)
        expect(resource.gold).toBe(28)
        expect(calculateGold(8)).toBe(1)
        expect(resource.gold).toBe(27)
        expect(calculateGold(9)).toBe(1)
        expect(resource.gold).toBe(26)
        expect(calculateGold(10)).toBe(1)
        expect(resource.gold).toBe(25)
        expect(calculateGold(11)).toBe(1)
        expect(resource.gold).toBe(24)
        expect(calculateGold(12)).toBe(2)
        expect(resource.gold).toBe(22)
      })
    })
  })
})
